---
- name: removing the httpd package from webservers
  hosts: webserver
  become: yes
  tasks:
    - name: remove httpd
      ansible.builtin.yum:
        name: httpd
        state: absent
- name: removing mariadb server
  hosts: dbserver
  become: yes
  tasks:
    - name: remove mariadb
      ansible.builtin.yum:
        name: mariadb
        state: absent



